language: node_js
node_js:
  - '8'
  - '6'
before_install:
  - npm install -g babel-cli
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    repo: revelrylabs/possum
    tags: true
    node: '8'
